"""20220727_roletablefix

Revision ID: 2c973987b94d
Revises: 9e33ad874c6d
Create Date: 2022-07-28 16:28:03.159933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c973987b94d'
down_revision = '9e33ad874c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('user_roles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'user_id')
    op.drop_column('user_roles', 'role_id')
    # ### end Alembic commands ###
