"""20220726_relationshipFixes

Revision ID: 70067137d4b7
Revises: 4ef3ddffc0af
Create Date: 2022-07-26 15:01:21.393775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70067137d4b7'
down_revision = '58c054a13660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('locality', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_address_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_address_id_fkey', 'users', 'address', ['address_id'], ['address_id'])
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('users_address_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_address_fkey', 'users', 'address', ['address'], ['address_id'])
    op.drop_column('users', 'address_id')
    op.drop_column('address', 'locality')
    # ### end Alembic commands ###
