"""20220727_1210_start_date

Revision ID: 958b86fd6881
Revises: 70067137d4b7
Create Date: 2022-07-27 12:16:12.576196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958b86fd6881'
down_revision = '70067137d4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'start_date')
    # ### end Alembic commands ###
