"""20220727_roletables

Revision ID: 9e33ad874c6d
Revises: 958b86fd6881
Create Date: 2022-07-28 16:15:48.311346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e33ad874c6d'
down_revision = '958b86fd6881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user_roles',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
